authentication/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='authentication'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'/sign_in',views.sign_in,name='sign_in'),
    #url(r'about_us$',views.about_us,name='about_us'),
    #url(r'contact_us$',views.contact_us,name='contact_us'),
    #path('login/',auth_views.LoginView.as_view(template_name='authentication/log_in.html'),name='sign_in'),
    path('logout/',auth_views.LogoutView.as_view(template_name='authentication/logout.html'),name='student-logout'),
 ]

tnp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from authentication import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^ccpd', include('authentication.urls', namespace="authentication")),
    url(r'^student/', include('student.urls', namespace="student")),
    url(r'^coordinator/', include('coordinator.urls', namespace="coordinator")),
    url(r'^administrator/', include('administrator.urls', namespace="administrator")),
    url(r'^ccpd/admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^company/', include('company.urls', namespace="company")),
    path('password_reset/',
    auth_views.PasswordResetView.as_view(template_name = 'account/password_reset.html'),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})',
        views.activate_account, name='activate'),
    ]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.db import models
from django.utils import timezone
from student.models import StudentUser
from PIL import Image
from django.urls import reverse


class Student_Profile(models.Model):
	user_id = models.IntegerField()
	image = models.ImageField( default = 'default.jpg' , upload_to = 'profile_pics')

	def __str__(self):
		return self.user.username + 'Profile'

	# def save(self, *args, **kwargs):
	# 	super().save()
		
	# 	img = Image.open(self.image.path)
	# 	if img.height > 300 or img.width > 300:
	# 		output_size = (300, 300)
	# 		img.thumbnail(output_size)
	# 		img.save(self.image.path)

coordinator/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User, Group 
from django.dispatch import receiver
from django.db.models.signals import post_save
from administrator.models import Branch
from django.utils import timezone
from django.core.validators import validate_comma_separated_integer_list
from company.models import Details
from student.models import *




# class Coordinator(models.Model):
    
#     name = models.CharField(max_length = 120,null=True)
#     user = models.ForeignKey('student.StudentUser',on_delete=models.CASCADE,)
#     admissionNumber = models.IntegerField(primary_key=True)
#     branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
#     yearOfGraduation = models.IntegerField(null=False)
#     rollNumber = models.IntegerField(null=False)
    
#     BTECH = 'BT'
#     MTECH = 'MT'
#     MCA = 'MC'
#     MSC = 'MS'
#     MBA = 'MB'

#     COURSE_CHOICES = (
#         (BTECH, 'B. Tech'),
#         (MTECH, 'M. Tech'),
#         (MCA, 'MCA'),
#         (MSC, 'M. Sc'),
#         (MBA, 'MBA')
#     )

#     course = models.CharField(
#         max_length=2,
#         choices=COURSE_CHOICES,
#         default=BTECH,
#     )

#     def __str__(self) :
#         return str(self.admissionNumber)


# @receiver(post_save, sender=Coordinator)
# def ensure_profile_exists(sender, **kwargs):
#     if kwargs.get('created', False):
#         my_group = Group.objects.get(name='Coordinator')
#         coordinator = Coordinator.objects.get(user=kwargs.get('instance').user)
#         my_group.user_set.add(coordinator.user)

class Companies(models.Model):
    
    COMPANY_STATUS = (
        ('Yet to Fill CPNF', 'Yet to fill CPNF'),
        ('CPNF received, unscheduled', 'CPNF received, unscheduled'),
        ('OT scheduled', 'OT scheduled'),
        ('Interview scheduled' , 'Interview scheduled'),
        (' Results received' , ' Results received')
    )
    name = models.CharField(max_length = 120, primary_key=True)
    dateOfVisit = models.DateField(null = True)
    status = models.CharField(
        max_length=100,
        choices=COMPANY_STATUS,
        default='Yet to Fill CPNF',
    )
    ALIVE = 'Alive'
    DEAD = 'Dead'
    EXISTING_STATUS = (
        (ALIVE, 'Alive'),
        (DEAD, 'Dead'),
    )
    existing_status = models.CharField(
        max_length=100,
        choices=EXISTING_STATUS,
        default=ALIVE,
    )
    branchesAllowed = models.CharField(max_length=2000, blank=True, null=True,default='')

    other_fields_url = models.URLField(max_length=200,default='',null=True,blank=True)

    CGPA = models.FloatField(null=False, default = 7.0)
    companyID = models.ForeignKey(Details,on_delete = models.CASCADE, null = False)

    def __str__(self) :
        return str(self.name)

class Announcement(models.Model):
    BROADCAST_ANNOUNCEMENT = 'Broadcasting'
    ELIGIBLE_ANNOUNCEMENT = 'Eligible'
    TYPE_OF_ANNOUNCEMENT = (
        (BROADCAST_ANNOUNCEMENT, 'Broadcast'),
        (ELIGIBLE_ANNOUNCEMENT, 'Eligible_ones'),
    )
    type_of_announcement = models.CharField(
        max_length=20,
        choices=TYPE_OF_ANNOUNCEMENT,
        default=BROADCAST_ANNOUNCEMENT,
    )
    announcementid = models.CharField(max_length = 120, primary_key=True)
    user = models.IntegerField( null =False)
    datePublished = models.DateField(default=timezone.now)
    text = models.TextField(max_length=500)
    company = models.ForeignKey(Companies,on_delete = models.CASCADE, null = True)

    def __str__(self) :
        return str(self.announcementid)

    @staticmethod
    def getCompanyName(self):
        return self.company.name

authentication/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Student_Profile

class StudentRegisterForm(UserCreationForm):
	email = forms.EmailField()
	class Meta:
		model = User
		fields = [ 'username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()
	class Meta:
		model = User
		fields = [ 'username', 'email']

class ProfileUpdateForm(forms.ModelForm):
	class Meta:
		model = Student_Profile
		fields = ['image']

authentication/views.py
from __future__ import unicode_literals
from django.contrib.auth import authenticate,login,logout
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.models import User
from .forms import StudentRegisterForm
from home.models import *
from company.forms import ContactForm
from django.core.mail import send_mail
from student.models import *
from django.db.models import Q
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from student.forms import *
from student.models import *
from django.core.mail import send_mail
from django.http import HttpResponse
import bcrypt
from django.contrib import messages

##### VALIDATION FOR FINAL YEARS #####
### ENTER the
#Group checking functions
def is_student(user):
	return user.groups.filter(name='Student').exists()

def is_coordinator(user):
	return user.groups.filter(name='Coordinator').exists()

def is_administrator(user):
	return user.groups.filter(name='Administrator').exists()

def is_superuser(user):
	return user.is_superuser

# Views
def index(request):
	# if request.user.is_authenticated and request.user.is_active == True:
	# 	student_flag = is_student(request.user)
	# 	if is_student(request.user):
	# 		return redirect('student/')

	# 	elif is_coordinator(request.user):
	# 		return redirect('coordinator/')

	# 	elif is_administrator(request.user):
    # 			return redirect('administration/')

	# 	elif is_superuser(request.user):
	# 		return redirect('admin/')
	# 	else:
	# 		return render(request, 'home/index.html', None)
	# else:
	# 	return render(request, 'home/index.html', None)

    links = Links.objects.all()
    recruiters = pastRecruiters.objects.all()
    team = Team.objects.all()
    photos = PhotosNitw.objects.all()
    faq = FrequentlyAsked.objects.all()
    form = ContactForm(request.POST or None)

    # new logic!
    if request.method == 'POST':
        name = form.cleaned_data.get('name')
        mailid = form.cleaned_data.get('mailid')
        message = form.cleaned_data.get('message')
        saveDetails = ContactCompany(
            name=name,
            mailid=mailid,
            message=message
        )
        saveDetails.save()
        send_mail(
            name + ' contacting CCPD',
            message,
            'nagamraghu120117143@gmail.com',
            [mailid],
            fail_silently=True,
        )
    context = {'Recruiters':recruiters, 'Team':team, 'CampusPictures': photos, 'FAQs': faq,'form':form}
    print(recruiters)
    print(context)
    return render(request, 'home/index.html', context)

def get_student_data(username, password):
    # Checking is student or not
    user = StudentUser.objects.filter(Q(username=username) | Q(email=username) )
    # print(user)
    print(user)
    if len(user) == 0:
        stud_data = StudentData.objects.filter(registration_number=username).first()
        # print(stud_data)
        if stud_data is not None:
            user = StudentUser.objects.filter(id=stud_data.userid)

    if len(user) != 0:
        return user.get()
    else:
        return None

def sign_in(request):
    if request.method == "POST":
        # print(request.POST)
        username = request.POST['username']
        password = request.POST['password']

        student_user = get_student_data(username, password)
        user =None
        if user is None and student_user is None:
            messages.error(request , 'Invalid Username / Password')
            return render(request, 'authentication/log_in.html', {})
        else:
            if student_user is not None:
                print(student_user.id)
                student = StudentData.objects.get(userid = student_user.id)
                print(student.course)
                if not ((student.registration_number[2:4]=='17' and student.course in ['B Tech' ,'btech']) or (student.registration_number[2:4]=='18' and student.course in ['MCA' , 'Msc','Msc. Tech']) or (student.registration_number[2:4]=='19' and student.course in ['M Tech','mtech','MBA'])) :
                    messages.error(request , 'Not Authorized')
                    return render(request, 'authentication/log_in.html')

                if bcrypt.checkpw(password.encode('utf-8'), student_user.password.encode('utf-8')):
                    
                    login(request, student_user,'django.contrib.auth.backends.ModelBackend')
                    print('student_user',student_user)
                    print('in auth',request.user)
                    request.session['user'] = 'hello'
                    return redirect('/ccpd/student/studentDashboard/')
                    # try:
                    #     student = StudentData.objects.get(userid=request.user.id)
                    #     print(student)
                    # except StudentData.DoesNotExist:
                else : 
                    messages.error(request , 'Invalid  / Password')
                    return render(request, 'authentication/log_in.html', )


            # Code comes here if student_user is not found.
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            if is_coordinator(request.user):
                return redirect('coordinator/')

            elif is_administrator(request.user):
                return redirect('administrator/')

            elif is_superuser(request.user):
                return redirect('/ccpd/admin')

            # except:
            #     return render(request, 'student/dashboard/pages/dashboard.html', {'error': 'Invalid username or password'})

    else:
        form = StudentRegisterForm()
    return render(request, 'authentication/log_in.html', {'form':form})

# def sign_out(request):
# 	logout(request)
# 	return redirect('/')

# def log_in(request):
# 	return render(request, 'authentication/log_in.html', {})

# def about_us(request):
# 	return render(request, 'authentication/resume.html', {})

# def contact_us(request):
# 	return render(request, 'authentication/contact.html', {})

# def sign_up(request):
#     return render(request,'account/index.html',{})

def activate_account(request, uidb64, token):
    try:
        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return HttpResponse('Your account has been activate successfully')
    else:
        return HttpResponse('Activation link is invalid!')

templates/authentication/add_company_form.html
{% extends 'authentication/template.html' %} {% block content %} {% load crispy_forms_tags %}



<div class="container">
    <div class="jumbotron">
        <div class="header">
            <h2> <u> {{ title }} </u></h2>
        </div>
        <br>
        <div class="content-section">
            <form method="POST">
                {% csrf_token %} {{ form|crispy }}
                

                <!--message block-->
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <!--message block-->
                <div class="form-check">
                <input
                    class="form-check-input"
                    type="checkbox"

                    onClick="toggle(this)"
                />
                <label class="form-check-label" for="cse">
                    Select All Branches and Courses </label
                >
                </br>
                <label class="form-check-label" >
                    ---------------------------------- OR ---------------------------------- </label
                >
                </br>
            </div>

                <div  id="newRow"></div>

                                                
                <button id="addRow" type="button" class="btn btn-primary  btn-lg btn-block">Add Branch & Courses</button><br>
                <br>
                <div class=" submit ">
                    <button type="submit " class="btn btn-info submit"> Submit </button>
                </div>

                
                <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
                <script type="text/javascript">
                    // add row
                    function toggle(source){
                        branch='cse,ece,civil,mech,meta,chem,eee,bio,mtech-cse-csis,mtech-cse-cse,c_est,c_wre,c_rsg,c_ctm,c_te,c_gte,c_ese,mtech-eee-pse,mtech-eee-ped,mtech-mech-te,mtech-mech-cim,mtech-mech-ae,mtech-mech-msed,mtech-mech-me,mtech-mech-md,mtech-mech-am,mtech-ece-ei,mtech-ece-acm,mtech-ece-vlsi,mtech-mme-im,mtech-mme-mt,mtech-che-ce,mtech-che-pc,mba-operations,mba-marketing,mba-hr,mba-finance,msct-p,msct-e,msct-i,mscm-am,mscm-msc,mscc-oc,mscc-mmc,phd-ce,phd-me,phd-ee,phd-ece,phd-mme,phd-cse,phd-bt,phd-maths,phd-phy,phd-che,phd-hss,phd-som,';
                        
                    }
                    $("#addRow").click(function () {
                        var html = '';
                        var options = '{{options_html | safe}}'
                        console.log(options)
                        html += '<div class="row" id="inputFormRow"><div class="col-md-10"><div class="col-sm-2"><select  name="branches" class="form-control branch" ><option value="">Select Branch</option>'+options+'</select></div>';
                        
                        html += '<i class="fas fa-minus-circle" id="removeRow"></i>';
                        html += '</div>';

                        $('#newRow').append(html);
                    });

                    // remove row
                    $(document).on('click', '#removeRow', function () {
                        $(this).closest('#inputFormRow').remove();
                    });

                $(".submit").click(function(event){
                    event.preventDefault()
                    list_branches =  $(".branch")
                    for (var i=0; i < list_branches.length ; i++){
                        if(i!=0)
                        branch += ","+ list_branches[i].value 
                        else
                        branch +=  list_branches[i].value
                    }
                    console.log(branch) 

                    $("#id_branchesAllowed").val(branch) 
                    $("form").submit()                  
                })

                
                </script>


            </form>


        </div>
    </div>

   
</div>
{% endblock %}

templates/authentication/form.html
{% extends 'authentication/template.html' %} {% block content %} {% load crispy_forms_tags %}



<div class="container">
    <div class="jumbotron">
        <div class="header">
            <h2> <u> {{ title }} </u></h2>
        </div>
        <br>
        <div class="content-section">
            <form method="POST">
                {% csrf_token %} {{ form|crispy }}
                
                <div class=" submit ">
                    <button type="submit " class="btn btn-info "> Submit </button>
                </div>

                <!--message block-->
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <!--message block-->

            </form>
        </div>
    </div>
</div>
<script>
    if ({{alert}} == 'True'){
        alert("asfasgf");
    } 
</script>
{% endblock %}

templates/authentication/index.html
{% load static %}
{% load i18n %}
{% load account socialaccount %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <title>CCPD, NIT Warangal</title>
    <!-- Meta-Tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <!-- <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script> -->
    <!-- //Meta-Tags -->
    <!-- Index-Page-CSS -->
    <link rel="stylesheet" href="{% static 'css/styleLogin.css' %}" type="text/css" media="all">
    <!-- onlinefonts -->
    <link href="//fonts.googleapis.com/css?family=Dosis:200,300,400,500,600,700,800" rel="stylesheet">
    <!-- //Custom-Stylesheet-Links -->
</head>

<body>
    <section class="login-wrap">
        <div class="main_w3agile">
            <input id="tab-1" type="radio" name="tab" class="sign-in" checked>
            <label for="tab-1" class="tab">Log In</label>
         <input id="tab-2" type="radio" name="tab" class="sign-up">
            <label for="tab-2" class="tab"></label> 
            <div class="login-form">
                <div class="signin_wthree">
                    <form method="post" action="/ccpd/sign_in/">
                        {% csrf_token %}
                        {% if redirect_field_value %}
                            <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                        {% endif %}
                        <div class="group">
                            <label for="username" class="label">WSDC Username</label>
                            <input id="username" type="text" name = "username" class="input" required>
                        </div>
                        <div class="group">
                            <label for="password" class="label">WSDC Password</label>
                            <input id="password" type="password" name = "password" class="input" data-type="password" required>
                        </div>
                        <div class="group">
                            <input id="check" type="checkbox" class="check" checked>
                            <label for="check">
                                <span class="icon"></span> Keep me Signed in</label>
                        </div>
                        <div class="group">
                            <button class="button" type="submit">{% trans "Sign In" %}</button>
                        </div>
                        <div class="hr"></div>
                        <div class="foot-lnk">

                           <h2><a href="{% url 'password_reset' %}">Forgot Password?</a></h2>
                        </div>
                        </br>
                        </br>
                         <!--message block-->
                        {% if messages %}
                            <ul class="messages center">
                                {% for message in messages %}
                                    <h5{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}
                                    </h5>
                                {% endfor %}
                            </ul>
                        {% endif %}
                <!--message block-->
                    </form>
                </div>

                {% comment %} <div class="signup_wthree">
                    <form class="signup" id="signup_form" method="post" action="{% url 'account_signup' %}">
                    {% csrf_token %}
                        {% if redirect_field_value %}
                        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                        {% endif %}
                        <div class="group">
                            <label for="username" class="label">Username</label>
                            <input id="username" name = "username" type="text" class="input" required>
                        </div>
                        <div class="group">
                            <label for="password1" class="label">Password</label>
                            <input id="password1" name = "password1" type="password" class="input" data-type="password" required>
                        </div>
                        <div class="group">
                            <label for="password2" class="label">Re-Enter Password</label>
                            <input id="password2" name = "password2" type="password" class="input" data-type="password" required>
                        </div>
                        <div class="group">
                            <label for="email" class="label">Email Address</label>
                            <input id="email" name = "email" type="email" class="input" required>
                        </div>
                        <div class="group">
                            <button type="submit" class="button">Sign Up</button>
                        </div>
                        <div class="hr"></div>
                        <div class="foot-lnk">
                            <label for="tab-1">Already Member? </label>
                        </div>
                    </form>

                </div> {% endcomment %}

            </div>
        </div>
    </section>
    <!-- //footer -->
    <!-- script for password match -->
    <script>
        window.onload = function () {
            document.getElementById("password1").onchange = validatePassword;
            document.getElementById("password2").onchange = validatePassword;
        }

        function validatePassword() {
            var pass2 = document.getElementById("password2").value;
            var pass1 = document.getElementById("password1").value;
            if (pass1 != pass2)
                document.getElementById("password2").setCustomValidity("Passwords Don't Match");
            else
                document.getElementById("password2").setCustomValidity('');
            //empty string means no validation error
        }
    </script>
    <!-- script for password match -->
</body>
<!-- //Body -->

</html>

templates/authentication/logged_out.html
{% extends 'authentication/template.html' %}
{% block content %}

<div class="container">
		<div class="jumbotron">
			<p>Logged out!</p>  
            <a href="{% url 'log_in'%}">Click here to login again.</a>
		</div>	
	</div>
{% endblock %}

templates/authentication/template.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Training and Placement,NIT Warangal</title>
	<link rel="stylesheet" href="{% static 'bootstrap.css' %}">
	{% comment %} <link rel="stylesheet" type="text/css" href="{% static 'scripts/authentication/app.css' %}"> {% endcomment %}
	<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet">
	<link rel="stylesheet" href="http://getbootstrap.com.vn/examples/equal-height-columns/equal-height-columns.css">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/foundation/5.5.0/css/foundation.css">
	
	<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css"><link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>
	{% comment %} <nav class="navbar navbar-inverse navbar-fix-top">
		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'authentication:index' %}">
					<div>Training and Placement</div>
				</a>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li class="active"><a href="{% url 'authentication:index' %}">Home <span class="sr-only">(current)</span></a></li>
					<li><a href="{% url 'authentication:about_us' %}">About</a></li>
					<li><a href="{% url 'authentication:contact_us' %}">Contact</a></li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li><a href="{% url 'account_signup' %}">Sign Up  <i class="fa fa-user-plus"></i></a></li>
					<li><a href="{% url 'account_login' %}">Login  <i class="fa fa-user"></i></a></li>
				</ul>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav> {% endcomment %}
	{% block content %}
	{% endblock %}
	<script src="https://kit.fontawesome.com/a076d05399.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.2/js/foundation/foundation.equalizer.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/trianglify/0.3.1/trianglify.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.2/js/foundation.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
</body>
</html>