coordinator/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name='coordinator'

urlpatterns = [
    # url(r'^registerCoordinator',views.registerCoordinator,name='registerCoordinator'),
    # url(r'^coordinatorDashboard',views.coordinatorDashboard,name='coordinatorDashboard'),
    # url(r'^addNewComapny',views.addNewCompany,name='addNewCompany'),
    # url(r'^updateCompanyStatus',views.updateCompanyStatus,name='updateCompanyStatus'),
    # url(r'^getCompanyStatus',views.getCompanyStatus,name='getCompanyStatus'),
    # url(r'^sendCompanyDetails',views.sendCompanyDetails,name='sendCompanyDetails'),
    # url(r'^checkApplicantsOfCompany',views.checkApplicantsOfCompany,name='checkApplicantsOfCompany'),
    # url(r'^placedStudents',views.placedStudents,name='placedStudents'),
    # url(r'^updateStudents',views.updateStudents,name='updateStudents'),
    # url(r'^updateAnnouncements',views.updateAnnouncement,name='updateAnnouncements'),
    # url(r'^createAnnouncements',views.createAnnouncement,name='createAnnouncements'),
    # url(r'^allCompanies', views.allCompanies, name='allCompanies'),
    # url(r'^searchStudent', views.searchStudent, name = 'searchStudent'),
    # path('companyApplicants/<slug:companyId>', views.companyApplicants, name = 'companyApplicants'),
    # path('export/', views.export_movies_to_xlsx, name='export'),
 ]

student/urls.py
from django.conf.urls import url,include
from django.urls import path
from . import views

app_name= 'student'

urlpatterns = [
    url(r'^registerStudent',views.registerStudent,name='registerStudent'),
    url(r'^studentDashboard',views.studentDashboard,name='studentDashboard'),
    url(r'^viewNewApplications',views.viewNewApplications,name='viewNewApplications'),
    url(r'^viewStatusOfApplication',views.viewStatusOfApplication,name='viewStatusOfApplication'),
    url(r'^viewProfile',views.viewProfile,name='viewProfile'),
    url(r'^uploadResume',views.uploadResume,name='uploadResume'),
    url(r'^addCGPA',views.addCGPA,name='addCGPA'),
    url(r'^showCalendar',views.showCalendar,name='showCalendar'),
    url(r'^contactTnp',views.contactTnp,name='contactTnp'),


    ##### coordinator urls #####

    url(r'^registerCoordinator',views.registerCoordinator,name='registerCoordinator'),
    url(r'^coordinatorDashboard',views.coordinatorDashboard,name='coordinatorDashboard'),
    url(r'^addNewComapny',views.addNewCompany,name='addNewCompany'),
    url(r'^deleteCompany',views.deleteCompany,name='deleteCompany'),
    url(r'^getCompanyStatus',views.getCompanyStatus,name='getCompanyStatus'),
    url(r'^sendCompanyDetails',views.sendCompanyDetails,name='sendCompanyDetails'),
    url(r'^checkApplicantsOfCompany',views.checkApplicantsOfCompany,name='checkApplicantsOfCompany'),
    url(r'^placedStudents',views.placedStudents,name='placedStudents'),
    url(r'^updateStudents',views.updateStudents,name='updateStudents'),
    url(r'^updateAnnouncements',views.updateAnnouncement,name='updateAnnouncements'),
    url(r'^createAnnouncements',views.createAnnouncement,name='createAnnouncements'),
    url(r'^allCompanies', views.allCompanies, name='allCompanies'),
    url(r'^searchStudent', views.searchStudent, name = 'searchStudent'),
    url(r'^viewCompanyDetails', views.viewCompanyDetails, name = 'viewCompanyDetails'),
    url(r'^applyForCompany', views.applyForCompany, name = 'applyForCompany'),
    url(r'^merge2Csv', views.merge2csv, name = 'merge2csv'),
    path('companyApplicants/<slug:companyId>', views.companyApplicants, name = 'companyApplicants'),
 ]

tnp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from authentication import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^ccpd', include('authentication.urls', namespace="authentication")),
    url(r'^student/', include('student.urls', namespace="student")),
    url(r'^coordinator/', include('coordinator.urls', namespace="coordinator")),
    url(r'^administrator/', include('administrator.urls', namespace="administrator")),
    url(r'^ccpd/admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^company/', include('company.urls', namespace="company")),
    path('password_reset/',
    auth_views.PasswordResetView.as_view(template_name = 'account/password_reset.html'),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})',
        views.activate_account, name='activate'),
    ]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

coordinator/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import  Companies, Announcement
from student.models import Coordinator

from django.forms import ModelForm

class DateInput(forms.DateInput):
    input_type = 'date'


class RegisterForm(forms.ModelForm):
    class Meta:
        model = Coordinator
        fields=[
            'name',
            'registration_number',
        ]

class CompaniesForm(forms.ModelForm):
    class Meta:
        model = Companies
        fields=[
            'name',
            'dateOfVisit',
            'status',
            'branchesAllowed',
            'CGPA',
            'other_fields_url',
            
            'companyID'
        ]
#widgets
        widgets = {
            'dateOfVisit': DateInput(),
        }



    def __init__(self,*args,**kwargs):
        super(CompaniesForm,self).__init__(*args,**kwargs)
        self.fields['dateOfVisit'].required=False
        self.fields['companyID'].required=False
		
class SearchCompany(forms.Form):
    name = forms.CharField(max_length=100)

class UpdatePlacementStatsForm(forms.Form):
    company = forms.CharField(max_length=100)
    students = forms.CharField(max_length=20000)
    APPLIED = 'A'
    INTERVIEW = 'I'
    PLACED = 'P'
    SELECTION_STATUS = (
        (INTERVIEW, 'interview'),
        (PLACED, 'placed'),
        (APPLIED, 'applied'),
    )
    status = forms.ChoiceField(choices = SELECTION_STATUS)

class AnnouncementForm(forms.ModelForm):
    class Meta:
        model = Announcement
        fields=[
            'announcementid',
            'company',
            'text',
            'datePublished',
            'type_of_announcement',
        ]
    def __init__(self,*args,**kwargs):
        super(AnnouncementForm,self).__init__(*args,**kwargs)
        self.fields['datePublished'].required=False

class SearchAnnouncement(forms.Form):
    announcementid = forms.CharField(max_length=10)

class UpdateAnnouncementForm(forms.Form):
    announcementid = forms.CharField(max_length=10)
    text = forms.CharField(max_length=20000)
    BROADCAST_ANNOUNCEMENT = 'Broadcasting'
    ELIGIBLE_ANNOUNCEMENT = 'Eligible'
    TYPE_OF_ANNOUNCEMENT = (
        (BROADCAST_ANNOUNCEMENT, 'Broadcast'),
        (ELIGIBLE_ANNOUNCEMENT, 'Eligible_ones'),
    )
    type_of_announcement = forms.ChoiceField(choices = TYPE_OF_ANNOUNCEMENT)


		

coordinator/views.py
from __future__ import unicode_literals
from django.contrib.auth import authenticate, login, logout , get_user_model
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.models import User
from .forms import RegisterForm
from django.contrib.auth.models import User, Group 
from student.models import Student
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .forms import CompaniesForm, SearchCompany, UpdatePlacementStatsForm
from .models import Companies
from administrator.models import Branch
from student.models import CompanyApplicants
from .models import Announcement
from .forms import AnnouncementForm, UpdateAnnouncementForm
from company.models import Details
from datetime import datetime, timedelta

from django.contrib import messages

# Views
flagDeleted = 0

# from openpyxl import Workbook
# from django.http import HttpResponse

# from .models import MovieCategory, Movie


# @login_required
# def export_movies_to_xlsx(request):
#     """
#     Downloads all movies as Excel file with a single worksheet
#     """
#     student_queryset = Student.objects.filter('rollNumber' = 'Companies__student').values('ID','name','CGPA','admissionNumber','branch')
    
#     response = HttpResponse(
#         content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
#     )
#     response['Content-Disposition'] = 'attachment; filename={date}-movies.xlsx'.format(
#         date=datetime.now().strftime('%Y-%m-%d'),
#     )
#     workbook = Workbook()
    
#     # Get active worksheet/tab
#     worksheet = workbook.active

#     worksheet.title = 'Movies'

#     # Define the titles for columns
#     columns = [
#         'ID',
#         'name',
#         'CGPA',
#         'admissionNumber',
#         'branch'
#     ]
#     row_num = 1

#     # Assign the titles for each cell of the header
#     for col_num, column_title in enumerate(columns, 1):
#         cell = worksheet.cell(row=row_num, column=col_num)
#         cell.value = column_title

#     # Iterate through all movies
#     for movie in student_queryset:
#         row_num += 1
        
#         # Define the data for each cell in the row 
#         row = [
#             movie.pk,
#             movie.name,
#             movie.CGPA,
#             movie.admissionNumber,
#             movie.branch,
#         ]
        
#         # Assign the data for each cell of the row 
#         for col_num, cell_value in enumerate(row, 1):
#             cell = worksheet.cell(row=row_num, column=col_num)
#             cell.value = cell_value

#     workbook.save(response)
#     if emails.filter(email=request.user.email).exists():
#         return HttpResponse("downloading in a queue ")
#     else:
#         return HttpResponse("unauthorized")

User = get_user_model()

# @login_required
# def coordinatorDashboard(request):
#     user = request.user
#     getAnnouncements = Announcement.objects.filter(
#         datePublished__gte=datetime.now() - timedelta(1), datePublished__lte=datetime.now())
#     listOfAnnouncements = []
#     for announcement in getAnnouncements:
#         if announcement.type_of_announcement == 'Broadcasting':
#             listOfAnnouncements.append(announcement)
#         else:
#             companyName = Announcement.getCompanyName(announcement)
#             company = Companies.objects.get(name=companyName)
#             if CompanyApplicants.objects.filter(student=student).filter(company=company).exists():
#                 listOfAnnouncements.append(announcement)

#     listOfCoordinators = User.objects.filter(groups__name='Coordinator')

#     print("hello")
#     print(listOfCoordinators)
#     emails = User.objects.filter(is_active=True).values_list(
#         'email', flat=True).filter(groups__name='Coordinator')
#     if emails.filter(email=request.user.email).exists():
#         context = {'listOfAnnouncements': listOfAnnouncements}
#         template = 'coordinator/dashboard/pages/dash.html'
#         return render(request, template, context)

#     else:
#         return HttpResponse("unauthorized")


# @login_required
# def registerCoordinator(request):
#     user = request.user
#     listOfCoordinators = User.objects.filter(groups__name='Student')
#     emails = User.objects.filter(is_active=True).values_list(
#         'email', flat=True).filter(groups__name='Coordinator')
#     if emails.filter(email=request.user.email).exists():
#         return HttpResponseRedirect('/coordinator/coordinatorDashboard')

#     else:
#         return HttpResponse("unauthorized")


# @login_required
# def addNewCompany(request):
#     form = CompaniesForm(request.POST or None)
#     if form.is_valid():
#         companyName = form.cleaned_data.get('name')
#         if Companies.objects.filter(name=companyName).exists():
#             HttpResponse("The Company name has already been added!")
#         else:
#             appl = form.save(commit=False)
#             appl.user = request.user
#             appl.save()
#             #return HttpResponse("successful")
#             return HttpResponseRedirect('/coordinator/coordinatorDashboard')

#     context = {'form': form, 'title': 'Add New Company'}
#     template = 'authentication/form.html'
#     return render(request, template, context)


# @login_required
# def updateCompanyStatus(request):
#     form = SearchCompany(request.POST or None)
#     if form.is_valid():
#         global flagDeleted
#         companyName = form.cleaned_data.get('name')
#         if Companies.objects.filter(name=companyName).exists():
#             Companies.objects.get(pk=companyName).delete()
#             flagDeleted = 1
#         elif flagDeleted == 1:
#             form = CompaniesForm(request.POST or None,
#                                  initial={'name': companyName})
#             if form.is_valid():
#                 print("hello")
#                 appl = form.save(commit=False)
#                 appl.user = request.user
#                 appl.save()
#                 #return HttpResponse("successful")
#                 messages.success(request, "successful")
#         else:
#             #print("The company was not added before!")
#             messages.error(request,"The company was not added before!")

#     context = {'form': form, 'title': 'Update Company Status'}
#     template = 'authentication/form.html'
#     return render(request, template, context)


# @login_required
# def getCompanyStatus(request):
#     form = SearchCompany(request.POST or None)
#     if form.is_valid():
#         companyName = form.cleaned_data.get('name')
#         if Companies.objects.filter(name=companyName).exists():
#             companyDetails = Companies.objects.filter(name=companyName)
#             statusOfCompany = companyDetails.values_list(
#                 'status', flat=True)[0]
#             #print(statusOfCompany)
#             #return HttpResponse(statusOfCompany)
#             messages.info(request, statusOfCompany)
#         else:
#             #return HttpResponse("The company was not added before!")
#             messages.error(request,"The company was not added before!")
            

#     context = {'form': form, 'title': 'View Company Status'}
#     template = 'authentication/form.html'
#     return render(request, template, context)


# @login_required
# def sendCompanyDetails(request):
#     form = SearchCompany(request.POST or None)
#     if form.is_valid():
#         companyName = form.cleaned_data.get('name')
#         if Companies.objects.filter(name=companyName).exists():
#             companyDetails = Companies.objects.filter(name=companyName)
#             branchesAllowed = companyDetails.values_list(
#                 'branchesAllowed', flat=True)[0]
#             cgpaAllowed = companyDetails.values_list('CGPA', flat=True)[0]
#             listOfBranches = branchesAllowed.split(',')
#             for branchElement in listOfBranches:
#                 branchName = Branch.objects.get(branchCode=branchElement)
#                 allowedByBranches = Student.objects.filter(
#                     branch=branchName).values_list('admissionNumber', flat=True)
#                 if allowedByBranches.exists():
#                     allowedByCGPA = allowedByBranches.filter(
#                         CGPA__gte=cgpaAllowed)  # cgpa greater than allowed
#                     for allowedStudent in allowedByCGPA:
#                         student = Student.objects.get(
#                             admissionNumber=allowedStudent)
#                         company = Companies.objects.get(name=companyName)
#                         newApplicant = CompanyApplicants(
#                             company=company, student=student)
#                         newApplicant.save()
#                     #print(allowedByCGPA)
#                     return HttpResponse(allowedByCGPA)
#         else:
#             #return HttpResponse("The company was not added before!")
#             messages.error(request,"The company was not added before!")

#     context = {'form': form, 'title': 'Send Company Details'}
#     template = 'authentication/form.html'
#     return render(request, template, context)


# @login_required
# def checkApplicantsOfCompany(request):
#     form = SearchCompany(request.POST or None)
#     if form.is_valid():
#         companyName = form.cleaned_data.get('name')
#         if Companies.objects.filter(name=companyName).exists():
#             companyDetails = Companies.objects.get(name=companyName)
#             listOfApplicants = CompanyApplicants.objects.filter(
#                 placementStatus='A').filter(company=companyDetails)
#             #print(listOfApplicants)
#             #messages.info(request,listOfApplicants)
#             return HttpResponse(listOfApplicants)
#         else:

templates/coordinator/dashboard/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
<!-- MDBootstrap Datatables  -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content='width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <meta name="description" content="Responsive sidebar template with sliding effect and dropdown menu based on bootstrap 3">
    <title>Dashboard</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <script type="text/javascript" src="https://addevent.com/libs/atc/1.6.1/atc.min.js" async defer></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/theme6.css' %}">


</head>
<style>
    .sidebar-wrapper .sidebar-brand>a {
        text-decoration: none;
    }
</style>

<body>
    <div class="page-wrapper chiller-theme toggled">
        <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
            <i class="fas fa-bars"></i>
        </a>
        <nav id="sidebar" class="sidebar-wrapper">
            <div class="sidebar-content">
                <div class="sidebar-brand">
                    <a href="#">Coordinator Portal</a>
                    <div id="close-sidebar">
                        <i class="fas fa-times"></i>
                    </div>
                </div>
                <div class="sidebar-header">
                    <div class="user-pic">
                        <img class="img-responsive rounded-circle" src="{% static 'img/pic1.jpeg'%}" alt="User picture" style="width:50px;height: 50px">
                    </div>
                    <div class="user-info">
                        <span class="user-name"><strong>{{ curr_user.name }}</strong></span>
                        <span class="user-role">CCPD associate</span>
                        <span class="user-status">
            {% comment %} <i class="fa fa-circle"></i>
            <span>Online</span> {% endcomment %}
                        </span>
                    </div>
                </div>

                <div class="sidebar-menu">
                    <ul>
                        <li class="text-center">
                            <a href="{% url 'student:studentDashboard'%}">
                                <span>Switch to Student</span>
                            </a>
                        </li>
                        <li class="header-menu">
                            <span>Tasks</span>
                        </li>

                        <li>
                            <a href="{% url 'student:addNewCompany'%}">
                                <i class="fa fa-user"></i>
                                <span>Add New/Update Company</span>
                            </a>
                        </li>

                         <li>
                            <a href="{% url 'student:deleteCompany'%}">
                                <i class="fa fa-tachometer-alt"></i>
                                <span>Delete Company</span>
                            </a>
                        </li> 

                        <li>
                            <a href="{% url 'student:getCompanyStatus'%}">
                                <i class="fa fa-calendar-check"></i>
                                <span>View Company Status</span>
                            </a>
                        </li>

                        {% comment %} <li>
                            <a href="{% url 'student:sendCompanyDetails'%}">
                                <i class="far fa-file"></i>
                                <span>Send Company Status</span>
                            </a>
                        </li> {% endcomment %}

                        <li>
                            <a href="{% url 'student:checkApplicantsOfCompany'%}">
                                <i class="fa fa-mouse-pointer"></i>
                                <span>Check Applicants</span>
                            </a>
                        </li>

                        <li>
                            <a href="{% url 'student:placedStudents'%}">
                                <i class="fa fa-calendar"></i>
                                <span>Placed Students</span>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'student:updateStudents'%}">
                                <i class="fa fa-calendar"></i>
                                <span>Update Students</span>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'student:updateAnnouncements'%}">
                                <i class="fa fa-calendar"></i>
                                <span>Update Announcement</span>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'student:createAnnouncements'%}">
                                <i class="fa fa-calendar"></i>
                                <span>Add Announcement</span>
                            </a>
                        </li>
                         <li>
                            <a href="{% url 'student:viewCompanyDetails'%}">
                                <i class="fa fa-calendar"></i>
                                <span>View Company Details</span>
                            </a>
                        </li>

                        <li>
                            <a href="{% url 'student:merge2csv'%}">
                                <i class="fa fa-calendar-check"></i>
                                <span>Merge 2 CSV files </span>
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- sidebar-menu  -->
            </div>
            <!-- sidebar-content  -->
            <div class="sidebar-footer" style="padding-top: 10px;">
                <a href="{% url 'account_logout' %}" title="Sign Out">
                    <i class="fa fa-power-off"></i>
                </a>
            </div>

        </nav>
        <!-- sidebar-wrapper  -->
        <main class="page-content" id="dashboard">
            <div class="container-fluid">
                {% comment %}
                <div class="wrapper" id="#wrapper"> {% endcomment %} {% block content %} {% endblock content %} {% comment %} </div> {% endcomment %}
            </div>
        </main>
        <!-- page-content" -->
    </div>
    <!-- page-wrapper -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
<!-- MDBootstrap Datatables  -->
<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>

<script type="text/javascript" src=" {% static 'js/jquery.js' %}"></script>

</html>

templates/coordinator/dashboard/mergedCsv.html
{% extends 'authentication/template.html' %}
{% block content %}
<style>
table, th, td {
  border: 1px solid black;
  padding: 5px;
  
}
table {
   
  border-spacing: 15px;
  width:75%;
}
h4 {
    margin : 75px 0px;
}
</style>
<div class = "container text-align-center mr-4">

<h4>Merged Data</h4>
  
  {{merged_file | safe }}
  <a href="#" onclick="download_table_as_csv('merged');">Download as CSV</a>
  
</div>
<script>
    function download_table_as_csv(table_id, separator = ',') {
    // Select rows from table_id
    var rows = document.querySelectorAll('table#' + table_id + ' tr');
    // Construct csv
    var csv = [];
    for (var i = 0; i < rows.length; i++) {
        var row = [], cols = rows[i].querySelectorAll('td, th');
        for (var j = 0; j < cols.length; j++) {
            // Clean innertext to remove multiple spaces and jumpline (break csv)
            var data = cols[j].innerText.replace(/(\r\n|\n|\r)/gm, '').replace(/(\s\s)/gm, ' ')
            // Escape double-quote with double-double-quote (see https://stackoverflow.com/questions/17808511/properly-escape-a-double-quote-in-csv)
            data = data.replace(/"/g, '""');
            // Push escaped string
            row.push('"' + data + '"');
        }
        csv.push(row.join(separator));
    }
    var csv_string = csv.join('\n');
    // Download it
    var filename = 'export_' + '{{company_name}}_' + table_id + '_' + new Date().toLocaleDateString() + '.csv';
    var link = document.createElement('a');
    link.style.display = 'none';
    link.setAttribute('target', '_blank');
    link.setAttribute('href', 'data:text/csv;charset=utf-8,' + encodeURIComponent(csv_string));
    link.setAttribute('download', filename);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);}
</script>


{% endblock content %}




        