student/urls.py
from django.conf.urls import url,include
from django.urls import path
from . import views

app_name= 'student'

urlpatterns = [
    url(r'^registerStudent',views.registerStudent,name='registerStudent'),
    url(r'^studentDashboard',views.studentDashboard,name='studentDashboard'),
    url(r'^viewNewApplications',views.viewNewApplications,name='viewNewApplications'),
    url(r'^viewStatusOfApplication',views.viewStatusOfApplication,name='viewStatusOfApplication'),
    url(r'^viewProfile',views.viewProfile,name='viewProfile'),
    url(r'^uploadResume',views.uploadResume,name='uploadResume'),
    url(r'^addCGPA',views.addCGPA,name='addCGPA'),
    url(r'^showCalendar',views.showCalendar,name='showCalendar'),
    url(r'^contactTnp',views.contactTnp,name='contactTnp'),


    ##### coordinator urls #####

    url(r'^registerCoordinator',views.registerCoordinator,name='registerCoordinator'),
    url(r'^coordinatorDashboard',views.coordinatorDashboard,name='coordinatorDashboard'),
    url(r'^addNewComapny',views.addNewCompany,name='addNewCompany'),
    url(r'^deleteCompany',views.deleteCompany,name='deleteCompany'),
    url(r'^getCompanyStatus',views.getCompanyStatus,name='getCompanyStatus'),
    url(r'^sendCompanyDetails',views.sendCompanyDetails,name='sendCompanyDetails'),
    url(r'^checkApplicantsOfCompany',views.checkApplicantsOfCompany,name='checkApplicantsOfCompany'),
    url(r'^placedStudents',views.placedStudents,name='placedStudents'),
    url(r'^updateStudents',views.updateStudents,name='updateStudents'),
    url(r'^updateAnnouncements',views.updateAnnouncement,name='updateAnnouncements'),
    url(r'^createAnnouncements',views.createAnnouncement,name='createAnnouncements'),
    url(r'^allCompanies', views.allCompanies, name='allCompanies'),
    url(r'^searchStudent', views.searchStudent, name = 'searchStudent'),
    url(r'^viewCompanyDetails', views.viewCompanyDetails, name = 'viewCompanyDetails'),
    url(r'^applyForCompany', views.applyForCompany, name = 'applyForCompany'),
    url(r'^merge2Csv', views.merge2csv, name = 'merge2csv'),
    path('companyApplicants/<slug:companyId>', views.companyApplicants, name = 'companyApplicants'),
 ]

tnp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from authentication import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^ccpd', include('authentication.urls', namespace="authentication")),
    url(r'^student/', include('student.urls', namespace="student")),
    url(r'^coordinator/', include('coordinator.urls', namespace="coordinator")),
    url(r'^administrator/', include('administrator.urls', namespace="administrator")),
    url(r'^ccpd/admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^company/', include('company.urls', namespace="company")),
    path('password_reset/',
    auth_views.PasswordResetView.as_view(template_name = 'account/password_reset.html'),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})',
        views.activate_account, name='activate'),
    ]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

student/views.py
from __future__ import unicode_literals
from django.contrib.auth import authenticate,login,logout
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.models import User
from .forms import *
from .models import Student
from django.shortcuts import redirect
from django.http import HttpResponse, HttpResponseRedirect , StreamingHttpResponse
from django.contrib.auth.decorators import login_required
from .models import *
from coordinator.models import *
from administrator.models import Branch
from datetime import datetime, timedelta
from django.core.mail import send_mail
from django.contrib import messages
import sys
import csv
import pandas as pd
import dask.dataframe as dd

noOfAnnouncements = 0
student  = None

def get_student_details(user_id):
    student_user = StudentUser.objects.get(id = user_id)
    resume_oject = Resume.objects.get(user = student_user)
    
    print(student_user)
    student_data = StudentData.objects.get(userid = user_id)
    name = student_data.name
    reg_number = student_data.registration_number
    student_mail_details = MailAll.objects.get(registration_number=reg_number)
    branch = student_data.branch
    year_of_graduation = (student_data.joining_year) 
    roll_number = student_data.roll_number
    cgpa = resume_oject.CGPA
    resume_url = resume_oject.resume
    address = student_data.address
    mob_number = student_data.mobile
    course = student_data.course
    email = student_user.email
    twelth_perc = resume_oject.twelth_perc
    tenth_perc = resume_oject.tenth_perc
    student = {
        'user_id' : user_id,
        'name' : name ,
        'admissionNumber' : reg_number,
        'branch' : branch,
        'course' : course,
        'yearOfGraduation' : year_of_graduation,
        'rollNumber' : roll_number,
        'CGPA' : cgpa,
        'address' : address,
        'mobileNumber' : mob_number,
        'profile_image' : student_data.profile_image,
        'resume_url' : resume_url,
        'email' :email,
        'student_email' : student_mail_details.email_id,
        'twelth_perc' : twelth_perc,
        'tenth_perc' : tenth_perc,
        'company_placed' : ''
        
    }
    # print(student)
    return student

@login_required
def studentDashboard(request):
    global noOfAnnouncements
    print(request.user)
    print(request.user.id)
    print("hi")
    student_user = StudentUser.objects.get(id = request.user.id)
    print(len(Resume.objects.filter(user=student_user)))
    if(not len(Resume.objects.filter(user=student_user))):
        return redirect('/ccpd/student/addCGPA')
       
    getAnnouncements = Announcement.objects.filter(datePublished__gte = datetime.now() - timedelta(1), datePublished__lte = datetime.now())
    student = get_student_details(request.user.id)
    listOfAnnouncements = []
    for announcement in getAnnouncements:
        if announcement.type_of_announcement == 'Broadcasting':
            listOfAnnouncements.append(announcement)
        else:
            company = Announcement.getCompanyName(announcement)
            
            if CompanyApplicants.objects.filter(student = request.user).filter(company = company).exists():
                listOfAnnouncements.append(announcement)
        
        global noOfAnnouncements
        noOfAnnouncements = len(listOfAnnouncements)
        
    # student = Student.objects.get(user = request.user)

    
    return render(request, 'student/dashboard/pages/dashboard.html', {'student':student,'noOfAnnouncements': noOfAnnouncements, 'listOfAnnouncements':listOfAnnouncements  })

@login_required
def registerStudent(request):
    user = request.user
    branches = Branch.objects.all()
    if Student.objects.filter(user = user).exists() :
        
        return HttpResponseRedirect('/ccpd/student/studentDashboard')

    rollNumber = request.POST.get('rollNumber')

    if rollNumber != None:
        if Student.objects.filter(rollNumber = rollNumber).exists():
            return HttpResponse("already registered")
        
        else:
            branchName = request.POST.get('branches')
            saveDetails = Student(
                name = request.POST.get('name'),
                user = request.user,
                admissionNumber = request.POST.get('admNumber'),
                rollNumber = rollNumber,
                branch = Branch.objects.get(branch = branchName),
                yearOfGraduation = request.POST.get('yearOfGraduation'),
                CGPA = request.POST.get('CGPA'),
                address = request.POST.get('address'),
                mobileNumber = request.POST.get('mobNo')
            )
            saveDetails.save()
            return HttpResponseRedirect('studentDashboard')
    return render(request,'Register/studentRegister.html',{'branches':branches})

@login_required
def viewNewApplications(request):
    student_user = StudentUser.objects.get(id = request.user.id)
    print(len(Resume.objects.filter(user=student_user)))
    if(not len(Resume.objects.filter(user=student_user))):
        return redirect('/ccpd/student/addCGPA')
    if request.method == 'GET':
        student = get_student_details(request.user.id)
        all_companies = Companies.objects.filter(CGPA__lte = student['CGPA'] , existing_status='Alive')
        print(all_companies)
        final_companies= []
        for company in all_companies:
            branches = company.branchesAllowed
            
            if(branches == None ):
                continue 
            listOfBranches = branches.split(',')
            resume_object = Resume.objects.get(user= request.user)
            if resume_object.branch in listOfBranches:
                final_companies.append(company)


        ## check eligibility
        context = {'eligibleCompanies' : final_companies ,'student' : student}
        return render(request,'student/showCompanies.html',context)
    if request.method == 'POST': 
        student = get_student_details(request.user.id)

        user = request.user
        company = CompanyApplicants.objects.filter(student = user).filter(placementStatus = 'N')
        print(company)
        context = {'eligibleCompanies' : company, 'student':student}
        companyName = request.POST.get('nameOfCompany')
        print(companyName, "hello")
        
        if companyName != None :
            companyDetails = Companies.objects.get(name = companyName)
            context = {'company_details' : companyDetails , 'student' : student , }
            return render(request , 'student/company_application_form.html' , context)
            
            
        return render(request,'student/showCompanies.html',context)

@login_required
def applyForCompany(request):
    student_user = StudentUser.objects.get(id = request.user.id)
    print(len(Resume.objects.filter(user=student_user)))
    if(not len(Resume.objects.filter(user=student_user))):
        return redirect('/ccpd/student/addCGPA')
    companyName = request.POST.get('company')
    student_id = request.POST.get('student_id')
    print(companyName)
    print(student_id)
    student_user = StudentUser.objects.get(id=student_id)
    student = get_student_details(student_id)
    if CompanyApplicants.objects.filter(company=companyName).filter(student=student_user).exists():
        messages.error(request , "You have already Applied for this Company")
        companyDetails = Companies.objects.get(name = companyName)
        context = {'company_details' : companyDetails , 'student' : student , }
        return render(request , 'student/company_application_form.html' , context)
    else: 
        companyDetails = Companies.objects.get(name = companyName)
        applicantData = CompanyApplicants()
        applicantData.student = StudentUser.objects.get(id=student_id)
        applicantData.company = companyDetails
        applicantData.placementStatus = 'A'
        applicantData.save()

        text_to_be_sent = 'Dear ' + student['name'] + ',\n' + 'You have successfully applied to be a part of the placement drive for the company - ' +  companyName + '. We will be reaching out to you with further notifications about the process.\n' + 'Best Regards\n' + 'CCPD.'
        send_mail(
            'Application Confirmation',
            text_to_be_sent,
            'taps@nitw.ac.in',
            [request.user.email],
            fail_silently=True,
        )
        
        return redirect('/ccpd/student/viewNewApplications')
# login_required
def viewStatusOfApplication(request):
    student_user = StudentUser.objects.get(id = request.user.id)
    print(len(Resume.objects.filter(user=student_user)))
    if(not len(Resume.objects.filter(user=student_user))):
        return redirect('/ccpd/student/addCGPA')
    student = get_student_details(request.user.id)
    user = request.user
    company = CompanyApplicants.objects.filter(student = user).exclude(placementStatus = 'N').exclude(placementStatus = 'R')
    return render(request,'student/showApplied.html',{'eligibleCompanies':company, 'student':student})

@login_required
def viewProfile(request):
    student_user = StudentUser.objects.get(id = request.user.id)
    print(len(Resume.objects.filter(user=student_user)))
    if(not len(Resume.objects.filter(user=student_user))):
        return redirect('/ccpd/student/addCGPA')
    student = get_student_details(request.user.id)

    resumeUploaded = False
    resume_url = ""
    if Resume.objects.filter(user = request.user).exists():
        resumeUploaded = True
        resume_url = Resume.objects.get(user=request.user).resume
    
    return render(request,'student/dashboard/pages/profile.html',{'student':student, 'resumeUploaded': resumeUploaded, 'resume_url' :resume_url })

@login_required
def uploadResume(request):
    # student = Student.objects.get(user = request.user)
    # print(request.POST.get('educationAll'))

    # if request.POST.get('educationAll') != None:
    #     education = request.POST.get('educationAll')

templates/student/dashboard/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
<!-- MDBootstrap Datatables  -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content='width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <meta name="description" content="Responsive sidebar template with sliding effect and dropdown menu based on bootstrap 3">
    <title>Dashboard</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

    <script type="text/javascript" src="https://addevent.com/libs/atc/1.6.1/atc.min.js" async defer></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/theme6.css' %}">



</head>
<style>
    .sidebar-wrapper .sidebar-brand>a {
        text-decoration: none;
    }
</style>

<body>
    <div class="page-wrapper chiller-theme toggled">
        <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
            <i class="fas fa-bars"></i>
        </a>
        <nav id="sidebar" class="sidebar-wrapper">
            <div class="sidebar-content">
                <div class="sidebar-brand">
                    <a href="#">Student Portal</a>
                    <div id="close-sidebar">
                        <i class="fas fa-times"></i>
                    </div>
                </div>
                <div class="sidebar-header">
                    <div class="user-pic">
                        <img class="img-responsive rounded-circle" src="{% static 'img/pic1.jpeg'%}" alt="User picture" style="width:50px;height: 50px">
                    </div>
                    <div class="user-info">
                        <span class="user-name">
            <strong>{{student.name}}</strong>
          </span>
                        <span class="user-role">{{student.branch.course}} , {{student.branch}}</span>
                        </span>
                    </div>
                </div>

                <div class="sidebar-menu">
                    <ul>
                        {% comment %} {% for group in user.groups.all %}
                        {% if group.name == 'Coordinator' %} {% endcomment %}
                        <li class="text-center">
                                   <a href="{% url 'student:coordinatorDashboard'%}">
                                       <span>Switch to Coordinator</span>
                                   </a>
                               {% comment %} </li>{% endif %}{% endfor %} {% endcomment %}
                        <li class="header-menu">
                            <span>General</span>
                        </li>

                        <li >
                            <a href="{% url 'student:viewProfile'%}">
                                <i class="fa fa-user"></i>
                                <span >My Profile</span>
                            </a>
                        </li>

                        <li>
                            <a href="{% url 'student:studentDashboard'%}">
                                <i class="fa fa-tachometer-alt"></i>
                                <span>Dashboard</span>
                                
                            </a>
                        </li>

                        <li>
                            <a href="{% url 'student:viewStatusOfApplication'%}">
                                <i class="fa fa-calendar-check"></i>
                                <span>Status of Application</span>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'student:addCGPA'%}">
                                <i class="far fa-file"></i>
                                <span>Add /Update Details </span>
                            </a>
                        </li>
                        {% comment %} <li>
                            <a href="{% url 'student:uploadResume'%}">
                                <i class="far fa-file"></i>
                                <span>Add /Update Resume</span>
                            </a>
                        </li> {% endcomment %}

                        <li>
                            <a href="{% url 'student:viewNewApplications'%}">
                                <i class="fa fa-mouse-pointer"></i>
                                <span>Apply For Company</span>
                            </a>
                        </li>

                        {% comment %} <li>
                            <a href="{% url 'student:showCalendar'%}">
                                <i class="fa fa-calendar"></i>
                                <span>Calendar</span>
                            </a>
                        </li> {% endcomment %}
                    </ul>
                </div>
                <!-- sidebar-menu  -->
            </div>
            <!-- sidebar-content  -->
            <div class="sidebar-footer" style="padding-top: 10px;">
                {% comment %} <a href="#" title="Announcements">
                    <i class="fa fa-bell"></i>
                    <span class="badge badge-pill badge-warning notification">{{noOfAnnouncements}}</span>
                </a>
                <a href="#" title="Messages">
                    <i class="fa fa-envelope"></i>
                    <span class="badge badge-pill badge-success notification">7</span>
                </a>
                <a href="#" title="Setting">
                    <i class="fa fa-cog"></i>
                    <span class="badge-sonar"></span>
                </a> {% endcomment %}
                <a href="{% url 'account_logout' %}" title="Sign Out">
                    <i class="fa fa-power-off"></i>
                </a>

            </div>
        </nav>
        <!-- sidebar-wrapper  -->
        <main class="page-content" id="dashboard">
            <div class="container-fluid">
                {% comment %}
                <div class="wrapper" id="#wrapper"> {% endcomment %} {% block content %} {% endblock content %} {% comment %} </div> {% endcomment %}
            </div>
        </main>
        <!-- page-content" -->
    </div>
    <!-- page-wrapper -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
<!-- MDBootstrap Datatables  -->



<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>

<script type="text/javascript" src=" {% static 'js/jquery.js' %}"></script>

</html>